import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import Provider from "@/components/custom/provider/provider";
import MobileOnly from "@/components/custom/container/mobile-only/mobile-only";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${GeistSans.variable}`}>
        <Provider>
          <MobileOnly>{children}</MobileOnly>
        </Provider>
      </body>
    </html>
  );
}
